<a href="https://colab.research.google.com/github/CodeHack-dot/AI-Powered-Healthcare-Diagnosis-Assistant/blob/main/AI_Powered_Healthcare_Diagnosis_Assistant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
# Load Dataset
df = pd.read_csv("/content/disease_dataset.csv")

In [ ]:
df.shape

(250, 13)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   fever                250 non-null    int64
 1   cough                250 non-null    int64
 2   headache             250 non-null    int64
 3   fatigue              250 non-null    int64
 4   vomiting             250 non-null    int64
 5   chest_pain           250 non-null    int64
 6   body_pain            250 non-null    int64
 7   runny_nose           250 non-null    int64
 8   shortness_of_breath  250 non-null    int64
 9   sore_throat          250 non-null    int64
 10  nausea               250 non-null    int64
 11  diarrhea             250 non-null    int64
 12  disease              250 non-null    object
dtypes: int64(12), object(1)
memory usage: 25.5+ KB

In [ ]:
df.describe()

,fever,cough,headache,fatigue,vomiting,chest_pain,body_pain,runny_nose,shortness_of_breath,sore_throat,nausea,diarrhea
count,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000,250.000000
mean,0.580000,0.584000,0.392000,0.756000,0.416000,0.232000,0.576000,0.412000,0.248000,0.420000,0.424000,0.248000
std,0.494549,0.493882,0.489176,0.430354,0.493882,0.422956,0.495182,0.493182,0.432718,0.494549,0.495182,0.432718
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [ ]:
df.isna().sum()

fever                  0
cough                  0
headache               0
fatigue                0
vomiting               0
chest_pain             0
body_pain              0
runny_nose             0
shortness_of_breath    0
sore_throat            0
nausea                 0
diarrhea               0
disease                0
dtype: int64

In [ ]:
X = df.drop('disease', axis = 1)
y = df['disease']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 24)

In [ ]:
model1=RandomForestClassifier(n_estimators=100,random_state=42)
model1.fit(X_train,y_train)

pred=model1.predict(X_test)
print("Accuracy:",accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

Accuracy: 1.0
                precision    recall  f1-score   support

   Common Cold       1.00      1.00      1.00         7
           Flu       1.00      1.00      1.00        10
Food Poisoning       1.00      1.00      1.00        16
       Malaria       1.00      1.00      1.00         6
     Pneumonia       1.00      1.00      1.00        11

      accuracy                           1.00        50
     macro avg       1.00      1.00      1.00        50
  weighted avg       1.00      1.00      1.00        50

In [ ]:
model= DecisionTreeClassifier(random_state=42)
model.fit(X_train,y_train)

pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

Accuracy: 0.96
                precision    recall  f1-score   support

   Common Cold       0.88      1.00      0.93         7
           Flu       0.90      0.90      0.90        10
Food Poisoning       1.00      1.00      1.00        16
       Malaria       1.00      0.83      0.91         6
     Pneumonia       1.00      1.00      1.00        11

      accuracy                           0.96        50
     macro avg       0.96      0.95      0.95        50
  weighted avg       0.96      0.96      0.96        50

In [ ]:
model=KNeighborsClassifier(n_neighbors=5)
model.fit(X_train,y_train)

pred=model.predict(X_test)
print("Accuracy:",accuracy_score(y_test,pred))
print(classification_report(y_test,pred))

Accuracy: 0.98
                precision    recall  f1-score   support

   Common Cold       1.00      1.00      1.00         7
           Flu       1.00      1.00      1.00        10
Food Poisoning       0.94      1.00      0.97        16
       Malaria       1.00      0.83      0.91         6
     Pneumonia       1.00      1.00      1.00        11

      accuracy                           0.98        50
     macro avg       0.99      0.97      0.98        50
  weighted avg       0.98      0.98      0.98        50

In [ ]:
print("\nBest Model :", best_name)
print(f"Best Accuracy : {best_acc*100:.2f}%")

Best Model : Random Forest
Best Accuracy : 100.00%

In [ ]:
joblib.dump(model1,"disease_model.pkl")
print("Model saved as disease_model.pkl")

Model saved as disease_model.pkl

In [ ]:
#Predict desease


import joblib

symptoms=["fever","cough","headache","fatigue","vomiting","chest_pain","body_pain","runny_nose","shortness_of_breath","sore_throat","nausea","diarrhea"]

doctor={
"Flu":"General Physician",
"Common Cold":"General Physician",
"Malaria":"Infectious Disease Specialist",
"Pneumonia":"Pulmonologist",
"Food Poisoning":"Gastroenterologist"
}

precautions={
"Flu":["Rest","Drink fluids","Monitor fever"],
"Common Cold":["Rest","Warm fluids","Steam inhalation"],
"Malaria":["Visit hospital","Stay hydrated","Take prescribed medicine"],
"Pneumonia":["Medical evaluation","Rest","Take medicines"],
"Food Poisoning":["ORS","Avoid oily food","Stay hydrated"]
}

model1=joblib.load("disease_model.pkl")
vals=[]
print("Enter 1 for Yes and 0 for No")
for s in symptoms:
    vals.append(int(input(f"{s}: ")))
pred=model1.predict([vals])[0]
prob=model1.predict_proba([vals])[0].max()*100
print("\nPredicted Disease:",pred)
# print(f"Confidence: {prob:.2f}%")
print("Doctor:",doctor[pred])
print("Precautions:")
for p in precautions[pred]:
    print("-",p)

Enter 1 for Yes and 0 for No
fever: 0